### ISSUE TITLE
The issue of Evaluation

### ISSUE THREAD

**Issue by zhaoxiang0715** [Alexbeast-CN/Detrive#2]
I'm so sorry to bother you. I was in running the CUDA_VISIBLE_DEVICES = 0. / leaderboard/scripts/run_evaluation. Sh"
The following error has occurred
> Registering the global statistics
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7f40a28dc290>
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 124, in __del__
    self._cleanup()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 157, in _cleanup
    self._agent_watchdog.stop()
  File "/mnt/papercode/22.Detrive/scenario_runner/srunner/scenariomanager/watchdog.py", line 72, in stop
    self._timer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
Could you help me solve this issue? Thank you very much!

**Comment by Daoming-Chen** [comment]
I'm sorry, I not using carla for really a long time, and I foget most of the trouble shooting tricks.
